{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4a8ea713-275f-41c4-8df3-9cbbf72ce31a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-06 13:56:49.721 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:49.846 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\pc1nva\\Anaconda3\\envs\\SheffieldNLP\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-06-06 13:56:49.848 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:49.849 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:50.356 Thread 'Thread-5': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:50.363 Thread 'Thread-5': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.971 Session state does not function when running a script without `streamlit run`\n",
      "2025-06-06 13:56:51.987 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.994 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-06 13:56:51.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "data = [\n",
    "    # Loneliness\n",
    "    (\"I reached out, but no one responded.\", \"loneliness\"),\n",
    "    (\"Every attempt to connect ends in silence.\", \"loneliness\"),\n",
    "    (\"I wandered through the game, unseen and unheard.\", \"loneliness\"),\n",
    "    (\"The emptiness was palpable; I was alone.\", \"loneliness\"),\n",
    "    (\"No matter where I went, I remained solitary.\", \"loneliness\"),\n",
    "    (\"I felt like a ghost passing through others.\", \"loneliness\"),\n",
    "    (\"Isolation was my only companion.\", \"loneliness\"),\n",
    "    (\"I existed, but no one acknowledged me.\", \"loneliness\"),\n",
    "    (\"The world was populated, yet I was alone.\", \"loneliness\"),\n",
    "    (\"I tried to engage, but was always ignored.\", \"loneliness\"),\n",
    "    (\"Being surrounded didn't alleviate my loneliness.\", \"loneliness\"),\n",
    "    (\"I moved through crowds, yet felt invisible.\", \"loneliness\"),\n",
    "    (\"My presence seemed to repel others.\", \"loneliness\"),\n",
    "    (\"I was a solitary figure in a busy world.\", \"loneliness\"),\n",
    "    (\"Attempts at connection were met with avoidance.\", \"loneliness\"),\n",
    "    (\"I felt like an outcast in every scene.\", \"loneliness\"),\n",
    "    (\"The game mirrored my feelings of being alone.\", \"loneliness\"),\n",
    "    (\"No matter how I tried, I couldn't find companionship.\", \"loneliness\"),\n",
    "    (\"I was present, but perpetually alone.\", \"loneliness\"),\n",
    "    (\"Loneliness was the game's constant theme.\", \"loneliness\"),\n",
    "\n",
    "    # Sadness\n",
    "    (\"The game's atmosphere left me feeling downcast.\", \"sadness\"),\n",
    "    (\"A deep sadness settled in as I played.\", \"sadness\"),\n",
    "    (\"I couldn't shake the melancholic mood.\", \"sadness\"),\n",
    "    (\"The experience evoked a profound sorrow.\", \"sadness\"),\n",
    "    (\"I felt a lingering sadness after playing.\", \"sadness\"),\n",
    "    (\"The game's tone was somber and affecting.\", \"sadness\"),\n",
    "    (\"I was moved to tears by the narrative.\", \"sadness\"),\n",
    "    (\"A sense of grief permeated the gameplay.\", \"sadness\"),\n",
    "    (\"The story touched on painful emotions.\", \"sadness\"),\n",
    "    (\"I felt emotionally drained after the game.\", \"sadness\"),\n",
    "    (\"The themes resonated with my own sadness.\", \"sadness\"),\n",
    "    (\"I was overwhelmed by a sense of loss.\", \"sadness\"),\n",
    "    (\"The game stirred up old wounds.\", \"sadness\"),\n",
    "    (\"I felt a heavy heart throughout.\", \"sadness\"),\n",
    "    (\"The narrative was a poignant reminder of sorrow.\", \"sadness\"),\n",
    "    (\"I was enveloped in a blue mood.\", \"sadness\"),\n",
    "    (\"The game's message was deeply saddening.\", \"sadness\"),\n",
    "    (\"I couldn't help but feel despondent.\", \"sadness\"),\n",
    "    (\"The experience was emotionally taxing.\", \"sadness\"),\n",
    "    (\"I was left with a sense of melancholy.\", \"sadness\"),\n",
    "\n",
    "    # Social Isolation\n",
    "    (\"I felt disconnected from the game's world.\", \"social isolation\"),\n",
    "    (\"There was a barrier between me and others.\", \"social isolation\"),\n",
    "    (\"I was excluded from every group I approached.\", \"social isolation\"),\n",
    "    (\"The game emphasized my separation from others.\", \"social isolation\"),\n",
    "    (\"I was on the outside looking in.\", \"social isolation\"),\n",
    "    (\"Interactions were superficial and fleeting.\", \"social isolation\"),\n",
    "    (\"I couldn't form any meaningful connections.\", \"social isolation\"),\n",
    "    (\"The game highlighted my social detachment.\", \"social isolation\"),\n",
    "    (\"I was always the observer, never the participant.\", \"social isolation\"),\n",
    "    (\"Attempts to join were met with resistance.\", \"social isolation\"),\n",
    "    (\"I felt like an intruder in every scene.\", \"social isolation\"),\n",
    "    (\"The game portrayed a world where I didn't belong.\", \"social isolation\"),\n",
    "    (\"I was perpetually sidelined.\", \"social isolation\"),\n",
    "    (\"Engagements were brief and unfulfilling.\", \"social isolation\"),\n",
    "    (\"I was isolated despite being among others.\", \"social isolation\"),\n",
    "    (\"The game underscored my social alienation.\", \"social isolation\"),\n",
    "    (\"I was present, but not included.\", \"social isolation\"),\n",
    "    (\"I felt like an outsider throughout.\", \"social isolation\"),\n",
    "    (\"The experience mirrored my feelings of exclusion.\", \"social isolation\"),\n",
    "    (\"I was surrounded, yet entirely alone.\", \"social isolation\"),\n",
    "\n",
    "    # Unknown\n",
    "    (\"I'm not sure how I feel after playing.\", \"unknown\"),\n",
    "    (\"The game left me with mixed emotions.\", \"unknown\"),\n",
    "    (\"I can't quite put my feelings into words.\", \"unknown\"),\n",
    "    (\"It was an unusual experience; I'm uncertain about it.\", \"unknown\"),\n",
    "    (\"I'm conflicted about the emotions it evoked.\", \"unknown\"),\n",
    "    (\"The game was thought-provoking, but I'm not sure how I feel.\", \"unknown\"),\n",
    "    (\"I need more time to process the experience.\", \"unknown\"),\n",
    "    (\"It's hard to describe the impact it had on me.\", \"unknown\"),\n",
    "    (\"I have a lot to think about after playing.\", \"unknown\"),\n",
    "    (\"The emotions are complex and hard to define.\", \"unknown\"),\n",
    "    (\"I'm left with questions rather than answers.\", \"unknown\"),\n",
    "    (\"The game was enigmatic; my feelings are too.\", \"unknown\"),\n",
    "    (\"I experienced a range of emotions, none clear.\", \"unknown\"),\n",
    "    (\"It's a puzzle, both in gameplay and emotion.\", \"unknown\"),\n",
    "    (\"I can't categorize how it made me feel.\", \"unknown\"),\n",
    "    (\"The experience was ambiguous and open-ended.\", \"unknown\"),\n",
    "    (\"I'm uncertain about the emotional journey it took me on.\", \"unknown\"),\n",
    "    (\"The game defies easy emotional labels.\", \"unknown\"),\n",
    "    (\"I'm still reflecting on what it meant to me.\", \"unknown\"),\n",
    "    (\"The feelings it stirred are indescribable.\", \"unknown\")\n",
    "]\n",
    "\n",
    "# Create DataFrame\n",
    "df = pd.DataFrame(data, columns=[\"text\", \"label\"])\n",
    "\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    return SentenceTransformer(\"paraphrase-MiniLM-L6-v2\")\n",
    "\n",
    "\n",
    "model = load_model()\n",
    "X = model.encode(df[\"text\"].tolist())\n",
    "y = df[\"label\"]\n",
    "\n",
    "# Train classifier\n",
    "clf = LogisticRegression(max_iter=1000)\n",
    "clf.fit(X, y)\n",
    "\n",
    "# Streamlit interface\n",
    "st.title(\"🎮 Post-Game Emotion Classifier\")\n",
    "st.write(\"Enter how you feel after playing the game *Loneliness*.\")\n",
    "\n",
    "user_input = st.text_area(\"How are you feeling?\", height=100)\n",
    "\n",
    "if st.button(\"Classify\"):\n",
    "    if user_input.strip() == \"\":\n",
    "        st.warning(\"Please enter some text.\")\n",
    "    else:\n",
    "        user_vector = model.encode([user_input])\n",
    "        prediction = clf.predict(user_vector)[0]\n",
    "        st.success(f\"🧠 The model thinks this indicates **{prediction.upper()}**.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
